wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1653370948
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      2:
      - 1
      - 9
      - 41
      - 55
      3:
      - 2
      - 23
      4: 3.9.12
      5: 0.12.16
      8:
      - 1
      - 4
      - 5
lr:
  desc: null
  value: 0.00026826576094071035
n_layer_1:
  desc: null
  value: 64
n_layer_2:
  desc: null
  value: 256
