wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.9.5
    start_time: 1653461588
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      2:
      - 1
      - 9
      - 41
      - 55
      3:
      - 7
      4: 3.9.5
      5: 0.12.16
      8:
      - 5
lr:
  desc: null
  value: 0.01
n_feat:
  desc: null
  value: 300
num_class:
  desc: null
  value: 1
