wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.8.1
    start_time: 1653536991
    t:
      1:
      - 1
      - 9
      - 55
      3:
      - 7
      - 23
      4: 3.8.1
      5: 0.12.16
      8:
      - 5
      - 9
layer1:
  desc: null
  value: 9000
lr:
  desc: null
  value: 0.01
num_class:
  desc: null
  value: 1
